language: node_js
node_js: '9'
dist: trusty
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_bc3701740180_key -iv $encrypted_bc3701740180_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 400 deploy_rsa
install:
  - echo "no action"
script:
  - echo "no action"
deploy:
- provider: script
  skip_cleanup: true
  script: ssh -i deploy_rsa -o "StrictHostKeyChecking no" root@water-fountains.org "cd /var/www/datablue_$TRAVIS_BRANCH && git stash && git pull origin $TRAVIS_BRANCH && npm install && npm run compile && pm2 delete datablue_$TRAVIS_BRANCH | echo && pm2 start www/main.js --name \"datablue_$TRAVIS_BRANCH\""
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^stable|develop$"
