language: node_js
node_js: '9'
dist: trusty
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_bc3701740180_key -iv $encrypted_bc3701740180_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 400 deploy_rsa
install:
  - npm install
script:
  # build app
  - npm run compile
  # gzip app
  - tar -czf package.tgz build
deploy:
- provider: script
  skip_cleanup: true
  script: scp -e "ssh -i deploy_rsa -o StrictHostKeyChecking=no" -r --delete-after --quiet $TRAVIS_BUILD_DIR/package.tgz root@water-fountains.org:/var/www/datablue_$TRAVIS_BRANCH && ssh -i deploy_rsa root@water-fountains.org -o "StrictHostKeyChecking no" "cd /var/www/datablue_$TRAVIS_BRANCH && tar -xzf package.tgz && rm package.tgz && rm -rf www_old && mv www www_old && mv build www && pm2 delete datablue_$TRAVIS_BRANCH | echo && pm2 start www/main.js --name \"datablue_$TRAVIS_BRANCH\""
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^stable|develop$"
