language: node_js
node_js: '9'
dist: trusty
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_e64b3d07f71e_key -iv $encrypted_e64b3d07f71e_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 400 deploy_rsa
install:
  - echo "no action"
script:
  - echo "no action"
deploy:
- provider: script
  skip_cleanup: true
  script: ssh -v -i deploy_rsa -o "StrictHostKeyChecking no" root@water-fountains.org "cd /var/www/datablue_$TRAVIS_BRANCH && git stash && git pull origin $TRAVIS_BRANCH && npm install && npm run init_symlink_server && npm run compile && pm2 delete datablue_$TRAVIS_BRANCH | echo && pm2 start build/main.js --name \"datablue_$TRAVIS_BRANCH\""
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^stable|develop$"
after_success:
  - echo "Build successful. TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
after_failure:
  - echo "Build failed. TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"