name: Ubuntu

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "9"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - name: check
        run: |
          set -e
          cp .envTEMPLATE .env
          npm run dev &
          sleep 10
          curl localhost:3000
          kill %1 # stop npm run dev
          git stash
          npm run compile
          git stash
      - name: deploy
        if: ${{ github.repository == 'water-fountains/datablue' && github.event_name == 'push' && (github.ref == 'refs/heads/stable' ||  github.ref == 'refs/heads/develop') }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH }}
          SSH_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          sudo chmod 400 ~/.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          BRANCH=$(if [ "${{ github.ref }}" == "refs/heads/stable" ]; then echo "stable"; else echo "develop"; fi)
          ssh -v -i deploy.key deploy@water-fountains.org "cd \"/var/www/datablue_$BRANCH\" &&
            git stash &&
            npm run init_symlink_server &&
            npm run compile &&
            pm2 delete \"datablue_$BRANCH\" | echo &&
            pm2 start build/main.js --name \"datablue_$BRANCH\""
