name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "9"
      - run: npm install
      - name: check
        run: |
          set -e
          cp .envTEMPLATE .env
          npm run dev &
          sleep 10
          curl localhost:3000
          kill %1 # stop npm run dev
          git stash
          npm run compile
          git stash
      - name: deploy
        if: ${{ github.repository == 'water-fountains/datablue' && github.event_name == 'push' && (github.ref == 'stable' ||  github.ref == 'develop') }}
        env:
          encrypted_e64b3d07f71e_key: ${{secrets.encrypted_e64b3d07f71e_key}}
          encrypted_e64b3d07f71e_iv: ${{secrets.encrypted_e64b3d07f71e_iv}}
          branch: ${{ github.ref }}
        run: |
          openssl aes-256-cbc -K "$encrypted_e64b3d07f71e_key" -iv "$encrypted_e64b3d07f71e_iv" -in deploy_rsa.enc -out deploy_rsa -d
          chmod 400 deploy_rsa
          ssh -v -i deploy_rsa -o "StrictHostKeyChecking no" root@water-fountains.org "cd /var/www/datablue_$branch" &&
            git stash &&
            npm run init_symlink_server &&
            npm run compile &&
            pm2 delete \"datablue_$branch\" | echo &&
            pm2 start build/main.js --name \"datablue_$branch\""
